/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;
import java.sql.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author zlenzer
 */
public class MainForm extends javax.swing.JFrame {
  String MemID;
  String BkID;
  
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        bak = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        MemberID = new javax.swing.JTextField();
        BookID = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System");
        setBounds(new java.awt.Rectangle(100, 50, 0, 0));
        setIconImages(null);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Books-2-icon.png"))); // NOI18N
        jLabel1.setText("Library Management System");
        jLabel1.setToolTipText("Member Borrow book");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(153, 153, 253));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Java SE Assignment Project ");
        jLabel2.setOpaque(true);

        jButton1.setBackground(new java.awt.Color(230, 228, 228));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Borrow Book-50.png"))); // NOI18N
        jButton1.setText("Borrow Book");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 255), null, null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(230, 228, 228));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Return Book-50.png"))); // NOI18N
        jButton2.setText("Return Book");
        jButton2.setToolTipText("User eturn Book");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 255), null, null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(230, 228, 228));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Booking-50.png"))); // NOI18N
        jButton3.setText("Reserved Book");
        jButton3.setToolTipText("User eturn Book");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 255), null, null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(230, 228, 228));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add User-50.png"))); // NOI18N
        jButton4.setText("Add Member");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 255), null, null));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(230, 228, 228));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add User Filled-50.png"))); // NOI18N
        jButton5.setText("Update Member");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 255), null, null));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(230, 228, 228));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Generic Book File Type-50.png"))); // NOI18N
        jButton6.setText("ADD New Book");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 255), null, null));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(230, 228, 228));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Generic Book File Type Filled-50.png"))); // NOI18N
        jButton7.setText("Update Book");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 255), null, null));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        bak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Books-2-icon (1).png"))); // NOI18N

        jButton8.setBackground(new java.awt.Color(230, 228, 228));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit Sign-50.png"))); // NOI18N
        jButton8.setText("Sign Out");
        jButton8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 255), null, null));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(230, 228, 228));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Combo Chart-50.png"))); // NOI18N
        jButton9.setText("Reports");
        jButton9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 255), null, null));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        MemberID.setText("Member ID");
        MemberID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mousemove(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MemberIDMouseExited(evt);
            }
        });
        MemberID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberIDActionPerformed(evt);
            }
        });

        BookID.setText("Book ID");
        BookID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouse1(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BookIDMouseExited(evt);
            }
        });
        BookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MemberID, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(BookID)))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(bak, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(bak, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BookID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9)
                                .addGap(153, 153, 153))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jButton8)
                        .addGap(11, 11, 11)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Sign Out");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About Us");

        jMenuItem3.setText("Team");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Contact Us");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         MemID= MemberID.getText();
         BkID= BookID.getText();
        if(MemID.equalsIgnoreCase("Member ID")){
            JOptionPane.showMessageDialog(null, "Please Input Valid Member ID");
        }else if (BkID.equalsIgnoreCase("Book ID")){
            JOptionPane.showMessageDialog(null, "Please Input Valid Book ID");
        }else{
            Calendar cal=Calendar.getInstance();
            
            String date=String.valueOf(cal.get(Calendar.DATE));
            String month=String.valueOf(cal.get(Calendar.MONTH));
            int d=Integer.parseInt(month);
            d=d+1;
            month=String.valueOf(d);
            String year=String.valueOf(cal.get(Calendar.YEAR));
            
            cal.add(Calendar.DATE,14);
            
            String rdate=String.valueOf(cal.get(Calendar.DATE));
            String rmonth=String.valueOf(cal.get(Calendar.MONTH));
            d=Integer.parseInt(rmonth);
            d=d+1;
            rmonth=String.valueOf(d);  
            String ryear=String.valueOf(cal.get(Calendar.YEAR));
            
            String cdate=year+"-"+month+"-"+date;
        String sql="SELECT * FROM member WHERE userID LIKE '"+MemID+"'";
//Check user ID
            ConnectDB cn1=new ConnectDB();
            cn1.connectDB();
            int c= cn1.reccount(sql);
            if (c==1){
                //Check bookID if user ID is correct
                sql="SELECT * FROM book WHERE BookID LIKE '"+BkID+"'";
                cn1.connectDB();
                c= cn1.reccount(sql);
                if(c==1){
                    //check whether user exceed or not his/her barrow limit
                    sql="SELECT * FROM transsactions WHERE MemberID LIKE '"+MemID+"' AND Status = 0";
                    cn1.connectDB();
                    c= cn1.reccount(sql);
                    System.out.println(c);
                    if(c<3){
                        //check whether book is available
                        sql="SELECT * FROM transsactions WHERE BookID LIKE '"+BkID+"' AND Status = 0";
                        cn1.connectDB();
                        c= cn1.reccount(sql);
                        if(c<1){
                            //if book is available and user doesn't exceed limit, issue book
                            sql="INSERT INTO transsactions ( BDate, RDate, Status, MemberID, BookID) VALUES ( '"+year+"-"+month+"-"+date+"', '"+ryear+"-"+rmonth+"-"+rdate+"', '0', '"+MemID+"', '"+BkID+"')";
                            cn1.connectDB();
                            cn1.addMember(sql);
                            JOptionPane.showMessageDialog(null, "Transsaction added");
                            MemberID.setText("Member ID");
                            BookID.setText("Book ID");
                        }else{
                        //if book is not available, give message
                            JOptionPane.showMessageDialog(null, "Sorry! Book is not available");
                        }
                    }else{
                    //if user exceed limit,give message
                        JOptionPane.showMessageDialog(null, "Sorry! Borrowing limit excceded");
                    }
                }else{
                //give message that book ID is incorrect
                    JOptionPane.showMessageDialog(null, "Sorry! Invalid Book ID");
                }
            }else{
            //give message that member ID is incorrect
                JOptionPane.showMessageDialog(null, "Sorry! Invalid Member ID");
            }
         
             
   
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         MemID= MemberID.getText();
         BkID= BookID.getText();
        if(MemID.equalsIgnoreCase("Member ID")){
            JOptionPane.showMessageDialog(null, "Please Input Valid Member ID");
        }else if (BkID.equalsIgnoreCase("Book ID")){
            JOptionPane.showMessageDialog(null, "Please Input Valid Book ID");
        }else{
            //check transsaction
            String sql="SELECT * FROM transsactions WHERE MemberID LIKE '"+MemID+"' AND BookID LIKE '"+BkID+"' AND Status=0";
            ConnectDB cn1=new ConnectDB();
            cn1.connectDB();
            int c= cn1.reccount(sql);
            if(c==1){
                //check return is on date
                cn1.connectDB();
                ResultSet rs2=cn1.fetchData(sql);
                String date;
                
                try {
                    while(rs2.next()){
                        String id=rs2.getString(1);
                        //getting return date from db
                        date=rs2.getString(3);
                        char[] day=date.toCharArray();
                        
                        String temp;int rdate,rmonth,ryear;
                        
                        temp= String.valueOf(day, 8, 2);
                        rdate=Integer.parseInt(temp);
                        
                        temp= String.valueOf(day, 5, 2);
                        rmonth=Integer.parseInt(temp);
                        
                        temp= String.valueOf(day, 0, 4);
                        ryear=Integer.parseInt(temp);
                        
             //getting current date
            Calendar ccal=Calendar.getInstance();
                        
            int cdate=Integer.parseInt(String.valueOf(ccal.get(Calendar.DATE)));
            int cmonth=Integer.parseInt(String.valueOf(ccal.get(Calendar.MONTH)));
            cmonth++;
            int cyear=Integer.parseInt(String.valueOf(ccal.get(Calendar.YEAR)));
            //check return date
                   if(rdate>=cdate && rmonth >= cmonth && ryear>=cyear){
                   JOptionPane.showMessageDialog(null, "Return date is"+ryear+"-"+rmonth+"-"+rdate);
                   }else{
                       //accept return and update db
                   sql= "UPDATE library.transsactions SET Status = 1 WHERE transsactions.ID ="+id;
                   cn1.connectDB();
                   cn1.addMember(sql);
                   JOptionPane.showMessageDialog(null, "Transsaction done");
                   }     
                        
                        
                    }
                } catch (SQLException ex) {
                        System.out.println(ex.getMessage());
        
                }
            }else{
            JOptionPane.showMessageDialog(null, "No record found");
            }
        
        
        
        
        
        
        
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         MemID= MemberID.getText();
         BkID= BookID.getText();
        if(MemID.equalsIgnoreCase("Member ID")){
            JOptionPane.showMessageDialog(null, "Please Input Valid Member ID");
        }else if (BkID.equalsIgnoreCase("Book ID")){
            JOptionPane.showMessageDialog(null, "Please Input Valid Book ID");
        }else{
            String sql="SELECT * FROM reservations WHERE BookID LIKE"+BkID;
            
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           new RegForm().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new UpdateMember().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            new AddBook().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new UpdateBook().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        new Report().setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void BookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookIDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BookIDActionPerformed

    private void MemberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberIDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MemberIDActionPerformed

    private void mousemove(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mousemove
        MemberID.setText("");
    }//GEN-LAST:event_mousemove

    private void mouse1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouse1
        BookID.setText("");
    }//GEN-LAST:event_mouse1

    private void BookIDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookIDMouseExited
        String mem=BookID.getText();
        if(mem.length()==0){
            BookID.setText("Book ID");
        }
    }//GEN-LAST:event_BookIDMouseExited

    private void MemberIDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MemberIDMouseExited
        String mem1=MemberID.getText();
        if(mem1.length()==0){
            MemberID.setText("Member ID");
        }
    }//GEN-LAST:event_MemberIDMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
          
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BookID;
    private javax.swing.JTextField MemberID;
    private javax.swing.JLabel bak;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
